### PR TITLE
Added optionalDependencies to the list

### PR DESCRIPTION
**Pull request by okhomenko**
I'm keeping my build dependencies in optionalDependencies branch of package.json. It would be good to read this dependencies as the others.

### CODE REVIEW

**Comment by jackfranklin** [comment]
Hmm - given how common this option is (or uncommon, given I'd never heard of it), I'm a little hesitant to merge it in, especially given that you could alter the config yourself in your app to support this. Ideally I'd be keen to get some more +1s on this.

**Comment by okhomenko** [comment]
Right, this is exactly what I'm doing right now (altering config).

I'm using optionalDeps for stuff that are not critical for running in development or production environment (such as modules used in build process). So some gulp-* plugins I keep in devDependencies, some in optionalDependencies. From what I see in other projects, majority of them keep everything in devDependencies, and sometimes even in "dependencies".

Anyway it's not a big deal, just convenient way to separate modules.

**Comment by callumacrae** [comment]
You can specify it yourself when you initiate gulp-load-plugins:

```js
var plugins = require('gulp-load-plugins')({
  scope: ['dependencies', 'devDependencies', 'peerDependencies', 'optionalDependencies']
});
```

**Comment by jackfranklin** [comment]
Yup, I'd advise what @callumacrae said. If more people are using this additional option then I'd consider this change being merged, but not until then I'm afraid.

**Pull request closed without merging**
