### PR TITLE
Added renameFn

### LINKED ISSUE #82: camelize should just control camelcase
With `camelize: true` the name `gulp-front-matter` gets turned into `frontMatter`.
With `camelize: false` the name `gulp-front-matter` gets turned into `front-matter`.

So not only does the option control the camel case but also the stripping of the hyphen.
I think this should be split this into two options. Something along the lines of this https://repl.it/zZu/1 :

    var fnCamel = function(s) {
        return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
    }

    var fnStrip = function(s, camel) {
        return s.split('-').map(function(w, i){
            return (i !== 0 && camel) ? fnCamel(w) : w;
        }).join('')
    }

    var fnTransform = function(example, strip, camel) {
        if (strip) {
            return fnStrip(example, camel);
        } else {
            return example;
        }
    };

    var examples = [ "front-matter-thing", "front-matTer" ];
    var camels = [ true, false ];
    var strips = [ true, false ];

    examples.forEach(function(example){
      strips.forEach(function(strip){
        camels.forEach(function(camel){
          console.log("strip:", strip, "camel:", camel);
          console.log(" ", example, " -> ", fnTransform(example, strip, camel));
        });
      });
    });

### PR DESCRIPTION
**Pull request by callumacrae**
Resolves #82 cc/ @tcurdt

### CODE REVIEW

**Comment by jackfranklin** [comment]
This is awesome! :heart: 

Maybe a quick README addition to explain if you define `renameFn`, the `rename` option gets ignored? Then :+1:

**Comment by callumacrae** [comment]
Donee

**Comment by jackfranklin** [comment]
:+1: after this is there anything stopping us releasing 1.0.0 proper do you think?

**Comment by callumacrae** [comment]
I reckon #70 and #80 probably both need looking at, but it doesn't look like that many people are having problems so I'd go for it :)

**Pull request merged**
